from __future__ import annotations

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Incoming chatbot query payload."""

    question: str = Field(..., min_length=3, description="User question about the constitution.")


class CitationSchema(BaseModel):
    """Traceable citation returned with a chatbot answer."""

    chunk_id: str
    article_label: str | None = None
    page_number: int | None = None
    excerpt: str


class ChatResponse(BaseModel):
    """Standard non-streaming chatbot response."""

    answer: str
    citations: list[CitationSchema] = Field(default_factory=list)


class AgentAnswer(BaseModel):
    """Structured answer generated by the agent."""

    answer: str = Field(..., description="Concise answer grounded in the constitution context.")
    cited_chunk_ids: list[str] = Field(
        default_factory=list,
        description="Chunk identifiers used to support the answer.",
    )
    insufficient_context: bool = Field(
        default=False,
        description="True when the retrieved context is not enough to answer confidently.",
    )
